import toggleMenu from "./modules/toggleMenu";
import showBenefit from "./modules/showBenefit";
import slider from "./modules/slider";
import countTimer from "./modules/countTimer";
import sendForm from "./modules/sendForm";
import validateInput from "./modules/validateInput";
import calc from "./modules/calc";
import showSertificate from "./modules/showSertificate";
toggleMenu();
showBenefit();
slider();
countTimer("16 september 2021");
sendForm();
validateInput();
calc();
showSertificate();